name: Auto Create PR on Push

on:
  push:
    branches:
      - update-state-machine

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch all branches
        run: git fetch --all

      - name: Ensure update-state-machine is up-to-date
        run: |
          git checkout update-state-machine
          git pull origin update-state-machine

      - name: Check for differences
        id: diff-check
        run: |
          git diff origin/main..origin/update-state-machine
          DIFF=$(git diff origin/main..origin/update-state-machine)
          echo "::set-output name=diff::${DIFF}"

      - name: Create Pull Request
        if: steps.diff-check.outputs.diff != ''
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Commit from update-state-machine'
          title: 'Automated Pull Request from update-state-machine'
          body: |
            This is an automated pull request to update the main branch with changes from `update-state-machine`.
          base: 'main'
          branch: 'update-state-machine'
          delete-branch: false
          draft: false
