name: Auto Create PR on Push

on:
  push:
    branches:
      - update-state-machine

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Commit from update-state-machine"
          title: "Automated Pull Request from update-state-machine"
          body: |
            This is an automated pull request to merge changes from the branch `update-state-machine`.
          branch: "auto-pr-${{ github.run_number }}"
          base: "main"
          delete-branch: true
          draft: false