name: Download from S3 and Create PR

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  download_s3_and_create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Download from S3
        run: |
          mkdir -p src/stateMachine
          if ! aws s3 cp s3://legal-ai-compliance-data-production/2024-06-27_02:10:46/user-manifest.json ./src/stateMachine/test.json; then
            echo "File does not exist in S3, exiting workflow successfully."
            exit 0
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Commit from update-s3-file'
          title: 'Automated Pull Request to update files from S3'
          body: |
            This is an automated pull request to update the main branch with changes from the `update-s3-file` branch.
          base: main
          branch: update-s3-file
          delete-branch: true
          draft: false
