name: Download from S3 and Create PR

on:
  schedule:
    - cron: '*/20 * * * *'
    # push:
    #   branches:
    #     - update-state-machine
  workflow_dispatch:

jobs:
  download_s3_and_create_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create mock file
        run: echo "This is a mock file." > mock-file.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Commit from update-s3-file'
          title: 'Automated Pull Request to update files from S3'
          body: |
            This is an automated pull request to update the main branch with changes from the `update-s3-file` branch.
          base: main
          branch: update-s3-file
          delete-branch: true
          draft: false
